fixed display function
yildiraykoyuncu/favorite-words pull request #13
Opened 2020-07-17 14:12 UTC by yildiraykoyuncu

close #1

2020-07-17 14:17 UTC, aleks2407 commented
Good job :) the only one thing , in demo word "All" is not capitalized.

2020-07-17 14:18 UTC, aleks2407 requested changes

2020-07-17 14:18 UTC, aleks2407 commented on scripts/user-actions/display.js
> +const displayHandler = (message = 'All words:', arrayToDisplay = words) => {
should be `all words:`

2020-07-17 14:58 UTC, abelRoland approved these changes
Good job! Thanks to do it!

2020-07-17 15:08 UTC, abelRoland approved these changes

2020-07-17 15:11 UTC, aleks2407 approved these changes

2020-07-18 08:44 UTC, Feruzteame approved these changes

2020-07-18 08:45 UTC, Feruzteame commented
nice !

2020-07-18 10:45 UTC, merged